# Generated by Django 5.2 on 2025-10-27 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PersonCountEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha y Hora"
                    ),
                ),
                (
                    "person_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Cantidad de Personas"
                    ),
                ),
                (
                    "event_id",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="ID del Evento"
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento de Detección",
                "verbose_name_plural": "Eventos de Detección",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="PersonTracking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "person_id",
                    models.CharField(max_length=50, verbose_name="ID de Persona"),
                ),
                (
                    "first_seen",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Primera Detección"
                    ),
                ),
                (
                    "last_seen",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Detección"
                    ),
                ),
                (
                    "detection_count",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Veces Detectado"
                    ),
                ),
            ],
            options={
                "verbose_name": "Seguimiento de Persona",
                "verbose_name_plural": "Seguimiento de Personas",
                "ordering": ["-last_seen"],
            },
        ),
    ]
